import type { EvaluationDetail } from "../types";
import { WaveLogo } from "./WaveLogo";

const RATING_LABEL: Record<number, string> = {
  1: "Does not meet Standards",
  2: "Needs Improvement",
  3: "Meets Standard",
  4: "Exceeds Standard",
  5: "Outstanding",
};

const RATING_COLOR: Record<number, string> = {
  1: "#b91c1c",
  2: "#c2550a",
  3: "#0077b6",
  4: "#15803d",
  5: "#166534",
};

function ReportContent({ ev }: { ev: EvaluationDetail }) {
  return (
    <div className="report-body">
      {/* Header */}
      <div className="report-header">
        <WaveLogo size={56} />
        <div className="report-header-text">
          <h1 className="report-school">PROPEL SWIM SCHOOL</h1>
          <h2 className="report-title">Instructor Evaluation Report</h2>
        </div>
      </div>

      <hr className="lane-divider" />

      {/* Info grid */}
      <div className="report-info-grid">
        <div className="report-info-item">
          <span className="report-info-label">Instructor</span>
          <span className="report-info-value">{ev.instructor_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Supervisor</span>
          <span className="report-info-value">{ev.supervisor_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Swim Level</span>
          <span className="report-info-value">{ev.level_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Stroke / Skill</span>
          <span className="report-info-value">{ev.skill_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Date</span>
          <span className="report-info-value">
            {new Date(ev.created_at).toLocaleDateString()}
          </span>
        </div>
        {ev.final_grade != null && (
          <div className="report-info-item">
            <span className="report-info-label">Final Grade</span>
            <span className="report-info-value" style={{ color: RATING_COLOR[ev.final_grade], fontWeight: 700 }}>
              {ev.final_grade} — {RATING_LABEL[ev.final_grade] ?? ""}
            </span>
          </div>
        )}
        <div className="report-info-item">
          <span className="report-info-label">Reevaluation</span>
          <span className="report-info-value" style={{ color: ev.needs_reevaluation ? "#c2550a" : "#15803d" }}>
            {ev.needs_reevaluation ? "Required" : "Not Required"}
          </span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Evaluation ID</span>
          <span className="report-info-value">#{ev.id}</span>
        </div>
      </div>

      <hr className="lane-divider" />

      {/* Ratings table */}
      {ev.ratings.length > 0 && (
        <div className="report-section">
          <h3 className="report-section-heading">Performance Ratings</h3>
          <table className="report-table">
            <thead>
              <tr>
                <th>Criterion</th>
                <th style={{ width: 80, textAlign: "center" }}>Score</th>
                <th>Assessment</th>
                <th>Comment</th>
              </tr>
            </thead>
            <tbody>
              {ev.ratings.map((r) => (
                <tr key={r.attribute_id}>
                  <td>{r.attribute_name}</td>
                  <td style={{ textAlign: "center", fontWeight: 800, fontSize: 18, color: RATING_COLOR[r.rating] }}>
                    {r.rating}
                  </td>
                  <td style={{ color: RATING_COLOR[r.rating], fontWeight: 600 }}>
                    {RATING_LABEL[r.rating] ?? "—"}
                  </td>
                  <td style={{ color: "#64748b", fontSize: 13 }}>{r.comment ?? "—"}</td>
                </tr>
              ))}
            </tbody>
          </table>

        </div>
      )}

      {/* Notes */}
      {ev.notes && (
        <div className="report-section">
          <h3 className="report-section-heading">Supervisor Notes</h3>
          <p className="report-notes">{ev.notes}</p>
        </div>
      )}

      {/* Footer */}
      <div className="report-footer">
        Generated by Propel Swim School Evaluation Portal &nbsp;·&nbsp; {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}

export function EvaluationReportModal({
  evaluation,
  onClose,
}: {
  evaluation: EvaluationDetail | null;
  onClose: () => void;
}) {
  if (!evaluation) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-toolbar no-print">
          <span style={{ fontWeight: 700, color: "#023e8a", fontSize: 15 }}>
            Evaluation Report — #{evaluation.id}
          </span>
          <div style={{ display: "flex", gap: 8 }}>
            <button onClick={() => window.print()}>🖨 Print / Save PDF</button>
            <button className="btn-add" onClick={onClose}>✕ Close</button>
          </div>
        </div>
        <ReportContent ev={evaluation} />
      </div>
    </div>
  );
}
