import type { EvaluationDetail } from "../types";
import { WaveLogo } from "./WaveLogo";

const RATING_LABEL: Record<number, string> = {
  1: "Remediate",
  2: "Meets Standard",
  3: "Exceeds Standard",
};

const RATING_COLOR: Record<number, string> = {
  1: "#b91c1c",
  2: "#0077b6",
  3: "#15803d",
};

function ReportContent({ ev }: { ev: EvaluationDetail }) {
  return (
    <div className="report-body">
      {/* Header */}
      <div className="report-header">
        <WaveLogo size={56} />
        <div className="report-header-text">
          <h1 className="report-school">PROPEL SWIM SCHOOL</h1>
          <h2 className="report-title">Instructor Evaluation Report</h2>
        </div>
        <div className="report-status-chip">
          <span className={ev.status === "SUBMITTED" ? "badge-submitted" : "badge-draft"}>
            {ev.status === "SUBMITTED" ? "Submitted" : "Draft"}
          </span>
        </div>
      </div>

      <hr className="lane-divider" />

      {/* Info grid */}
      <div className="report-info-grid">
        <div className="report-info-item">
          <span className="report-info-label">Instructor</span>
          <span className="report-info-value">{ev.instructor_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Supervisor</span>
          <span className="report-info-value">{ev.supervisor_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Swim Level</span>
          <span className="report-info-value">{ev.level_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Stroke / Skill</span>
          <span className="report-info-value">{ev.skill_name}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Session</span>
          <span className="report-info-value">{ev.session_label}</span>
        </div>
        <div className="report-info-item">
          <span className="report-info-label">Date</span>
          <span className="report-info-value">{ev.session_date}</span>
        </div>
        {ev.submitted_at && (
          <div className="report-info-item">
            <span className="report-info-label">Submitted At</span>
            <span className="report-info-value">
              {new Date(ev.submitted_at).toLocaleString()}
            </span>
          </div>
        )}
        <div className="report-info-item">
          <span className="report-info-label">Evaluation ID</span>
          <span className="report-info-value">#{ev.id}</span>
        </div>
      </div>

      <hr className="lane-divider" />

      {/* Ratings table */}
      {ev.ratings.length > 0 && (
        <div className="report-section">
          <h3 className="report-section-heading">Performance Ratings</h3>
          <table className="report-table">
            <thead>
              <tr>
                <th>Criterion</th>
                <th style={{ width: 80, textAlign: "center" }}>Score</th>
                <th>Assessment</th>
              </tr>
            </thead>
            <tbody>
              {ev.ratings.map((r) => (
                <tr key={r.attribute_id}>
                  <td>{r.attribute_name}</td>
                  <td style={{ textAlign: "center", fontWeight: 800, fontSize: 18, color: RATING_COLOR[r.rating_value] }}>
                    {r.rating_value}
                  </td>
                  <td style={{ color: RATING_COLOR[r.rating_value], fontWeight: 600 }}>
                    {RATING_LABEL[r.rating_value] ?? "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Rating legend */}
          <div className="report-legend">
            {[1, 2, 3].map((v) => (
              <span key={v} style={{ color: RATING_COLOR[v] }}>
                <strong>{v}</strong> = {RATING_LABEL[v]}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Notes */}
      {ev.notes && (
        <div className="report-section">
          <h3 className="report-section-heading">Supervisor Notes</h3>
          <p className="report-notes">{ev.notes}</p>
        </div>
      )}

      {/* Signature block */}
      <div className="report-signatures">
        <div className="report-sig-box">
          <div className="report-sig-line" />
          <p>Instructor Signature &amp; Date</p>
        </div>
        <div className="report-sig-box">
          <div className="report-sig-line" />
          <p>Supervisor Signature &amp; Date</p>
        </div>
      </div>

      {/* Footer */}
      <div className="report-footer">
        Generated by Propel Swim School Evaluation Portal &nbsp;·&nbsp; {new Date().toLocaleDateString()}
      </div>
    </div>
  );
}

export function EvaluationReportModal({
  evaluation,
  onClose,
}: {
  evaluation: EvaluationDetail | null;
  onClose: () => void;
}) {
  if (!evaluation) return null;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="modal-toolbar no-print">
          <span style={{ fontWeight: 700, color: "#023e8a", fontSize: 15 }}>
            Evaluation Report — #{evaluation.id}
          </span>
          <div style={{ display: "flex", gap: 8 }}>
            <button onClick={() => window.print()}>🖨 Print / Save PDF</button>
            <button className="btn-add" onClick={onClose}>✕ Close</button>
          </div>
        </div>
        <ReportContent ev={evaluation} />
      </div>
    </div>
  );
}
